#!/bin/bash
kubectl scale deployment messaging-app-deployment --replicas=3
echo "Checking running pods..."
kubectl get pods -l app=messaging-app
echo "Performing load test..."
wrk -t12 -c400 -d30s http://messaging-app-service:80
echo "Checking resource usage..."
kubectl top pods -l app=messaging-app