<<<<<<< HEAD
# messaging_app/.github/workflows/ci.yml
=======
>>>>>>> 505645a90e1769b894996680c0b2fbdc7f64c008
name: Django CI

on:
  push:
<<<<<<< HEAD
    branches:
      - main
  pull_request:

jobs:
  test:
=======
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
>>>>>>> 505645a90e1769b894996680c0b2fbdc7f64c008
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
<<<<<<< HEAD
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Django migrations
        run: |
          cd messaging_app
          python manage.py migrate

      - name: Run tests
        run: |
          cd messaging_app
          python manage.py test
=======
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 coverage

 
    - name: Run flake8 lint
      run: |
        echo "Running flake8..."
        flake8 messaging_app --max-line-length=100 --statistics
e
    - name: Run tests with coverage
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: test_db
      run: |
        echo "Running tests with coverage..."
        coverage run manage.py test
        coverage xml

 
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
>>>>>>> 505645a90e1769b894996680c0b2fbdc7f64c008
